version: "3"
services:
  rest-json:
    build: .
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rest-json
    ports:
      - "5000:4000"
